// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nest.Infrastructure;

#nullable disable

namespace Nest.Infrastructure.Migrations.Hotels
{
    [DbContext(typeof(ApplicationHotelDbContext))]
    partial class ApplicationHotelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Nest.Domain.ContactInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("char(36)");

                    b.Property<int>("LocationCode")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("ContactInfos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5243226f-6501-4a0f-af3a-dcc98668095d"),
                            Content = "İstanbul",
                            HotelId = new Guid("37c26834-c2fd-4574-843a-38fdd9474eb6"),
                            LocationCode = 34,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("7bbcedba-54a8-441e-a08b-14818c1ec8ee"),
                            Content = "İstanbul",
                            HotelId = new Guid("b9dc2b4c-5ab5-46bc-b523-6cd9e698e47c"),
                            LocationCode = 34,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("c97de36f-d632-42bc-b4d4-d90f35dbb1e0"),
                            Content = "İstanbul",
                            HotelId = new Guid("5988e09b-38e0-4769-b180-73fffbbd8d6b"),
                            LocationCode = 34,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("55b66f8f-1466-48b0-8254-d1f3861cd0e7"),
                            Content = "İstanbul",
                            HotelId = new Guid("c7ea298b-ff64-4688-a172-2f581a1115bb"),
                            LocationCode = 34,
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("0fc19e82-5d70-4998-91e1-bcafbbfe9a4b"),
                            Content = "İstanbul",
                            HotelId = new Guid("27dd1fe5-c906-4347-bfa0-67a109082b4f"),
                            LocationCode = 34,
                            Type = 3
                        });
                });

            modelBuilder.Entity("Nest.Domain.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37c26834-c2fd-4574-843a-38fdd9474eb6"),
                            HotelName = "Test 1"
                        },
                        new
                        {
                            Id = new Guid("b9dc2b4c-5ab5-46bc-b523-6cd9e698e47c"),
                            HotelName = "Test 2"
                        },
                        new
                        {
                            Id = new Guid("5988e09b-38e0-4769-b180-73fffbbd8d6b"),
                            HotelName = "Test 3"
                        },
                        new
                        {
                            Id = new Guid("c7ea298b-ff64-4688-a172-2f581a1115bb"),
                            HotelName = "Test 4"
                        },
                        new
                        {
                            Id = new Guid("27dd1fe5-c906-4347-bfa0-67a109082b4f"),
                            HotelName = "Test 5"
                        },
                        new
                        {
                            Id = new Guid("31de4b1d-fa48-4594-b85f-f43af0621dde"),
                            HotelName = "Test 6"
                        },
                        new
                        {
                            Id = new Guid("d8c31825-06d1-4a9e-b8a3-01aa3ba87299"),
                            HotelName = "Test 7"
                        },
                        new
                        {
                            Id = new Guid("873d9ced-962f-4ab2-94a5-5e19d401e604"),
                            HotelName = "Test 8"
                        },
                        new
                        {
                            Id = new Guid("53950c18-cb4e-462b-81e4-00aa4fd8dd62"),
                            HotelName = "Test 9"
                        },
                        new
                        {
                            Id = new Guid("dec8da0e-903c-4cab-9afc-0487f77d7069"),
                            HotelName = "Test 10"
                        });
                });

            modelBuilder.Entity("Nest.Domain.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("Nest.Domain.ContactInfo", b =>
                {
                    b.HasOne("Nest.Domain.Hotel", "Hotel")
                        .WithMany("ContactInfo")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Nest.Domain.Manager", b =>
                {
                    b.HasOne("Nest.Domain.Hotel", "Hotel")
                        .WithMany("Manager")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Nest.Domain.Hotel", b =>
                {
                    b.Navigation("ContactInfo");

                    b.Navigation("Manager");
                });
#pragma warning restore 612, 618
        }
    }
}
